import {
  assertSingleWordPaletteProperties,
  createColorMap,
  createPalette,
  keys,
  withAlpha,
} from "./colors.js";
import { JACK_BORDER_PALETTE } from "./jacks-color-theme.js";
import { defineTheme, featureGroup } from "./theme.js";
import type {
  ColorPair,
  FeatureGroup,
  Palette,
  SourceBackgroundPalette,
  SourceFontPalette,
} from "./theme.js";
import { createWorkbenchFeatureGroups } from "./workbench.js";

const MOCKUP_BACKGROUND_PALETTE = {
  black: "#24211c",
  editor: "#e4d7c4",
  panel: "#e2d7c8",
  popup: "#efe2cd",
  hover: "#d1c3b1",
  active: "#c2b4a2",
  guide: "#9c9083",
  accent: "#d7b250",
  success: "#a3c48f",
  danger: "#e1a09b",
  info: "#94bece",
  ember: "#dfa171",
  sand: "#d3b45f",
  moss: "#a3c48f",
  sky: "#94bece",
  mark: "#9f7abf",
  plum: "#b99bce",
  clay: "#e1a09b",
} as const satisfies SourceBackgroundPalette;

const MOCKUP_FONT_PALETTE = {
  text: "#24211c",
  muted: "#45423d",
  faint: "#655e55",
  ember: "#9b3b18",
  sand: "#5c5600",
  moss: "#006b3f",
  sky: "#005a9e",
  plum: "#733b9e",
  clay: "#a5305b",
} as const satisfies SourceFontPalette;

assertSingleWordPaletteProperties("background", MOCKUP_BACKGROUND_PALETTE);
assertSingleWordPaletteProperties("font", MOCKUP_FONT_PALETTE);

const MOCKUP_PALETTE = createPalette(
  MOCKUP_BACKGROUND_PALETTE,
  MOCKUP_FONT_PALETTE,
  JACK_BORDER_PALETTE,
);
const MOCKUP_FONT_COLORS = createColorMap(MOCKUP_FONT_PALETTE);

const mockupBorderIds = [
  "focusBorder",
  "sash.hoverBorder",
  "widget.border",
  "editorWidget.border",
  "editorWidget.resizeBorder",
  "editorHoverWidget.border",
  "window.activeBorder",
  "window.inactiveBorder",
  "textBlockQuote.border",
  "textSeparator.foreground",
  "toolbar.hoverOutline",
  "button.border",
  "button.secondaryBorder",
  "checkbox.border",
  "dropdown.border",
  "input.border",
  "inputOption.activeBorder",
  "inputValidation.errorBorder",
  "inputValidation.infoBorder",
  "inputValidation.warningBorder",
  "activityBar.border",
  "activityBar.activeBorder",
  "activityBarTop.activeBorder",
  "sideBar.border",
  "sideBarSectionHeader.border",
  "editorGroup.border",
  "editorGroupHeader.tabsBorder",
  "editorGroupHeader.border",
  "tab.activeBorder",
  "tab.activeBorderTop",
  "tab.border",
  "editor.findMatchBorder",
  "editorBracketMatch.border",
  "editorUnicodeHighlight.border",
  "editorOverviewRuler.border",
  "editorError.border",
  "editorWarning.border",
  "editorInfo.border",
  "editorHint.border",
  "diffEditor.border",
  "panel.border",
  "panelTitle.activeBorder",
  "panelInput.border",
  "terminal.border",
  "debugToolBar.border",
  "statusBar.border",
  "titleBar.border",
  "menu.border",
  "menu.selectionBorder",
  "menu.separatorBackground",
  "menubar.selectionBorder",
  "commandCenter.border",
  "commandCenter.inactiveBorder",
  "commandCenter.activeBorder",
  "notificationCenter.border",
  "notificationToast.border",
  "notifications.border",
  "pickerGroup.border",
  "settings.checkboxBorder",
  "settings.dropdownBorder",
  "settings.numberInputBorder",
  "settings.sashBorder",
  "settings.textInputBorder",
  "peekView.border",
  "welcomePage.tileBorder",
  "charts.lines",
] as const;

const mockupFocusBorderIds = [
  "focusBorder",
  "sash.hoverBorder",
  "activityBar.activeBorder",
  "activityBarTop.activeBorder",
  "tab.activeBorder",
  "tab.activeBorderTop",
  "panelTitle.activeBorder",
  "commandCenter.activeBorder",
  "inputOption.activeBorder",
  "editor.findMatchBorder",
] as const;

const mockupControlBorderIds = [
  "button.border",
  "button.secondaryBorder",
  "checkbox.border",
  "dropdown.border",
  "input.border",
  "settings.checkboxBorder",
  "settings.dropdownBorder",
  "settings.numberInputBorder",
  "settings.textInputBorder",
] as const;

const mockupOuterBorderIds = [
  "window.activeBorder",
  "activityBar.border",
  "sideBar.border",
  "editorGroup.border",
  "editorGroupHeader.tabsBorder",
  "editorGroupHeader.border",
  "panel.border",
  "terminal.border",
  "statusBar.border",
  "titleBar.border",
  "peekView.border",
] as const;

const mockupValidationBorderIds = [
  "inputValidation.errorBorder",
  "editorError.border",
] as const;

const mockupWarningBorderIds = [
  "inputValidation.warningBorder",
  "editorWarning.border",
] as const;

const mockupInfoBorderIds = [
  "inputValidation.infoBorder",
  "editorInfo.border",
  "editorHint.border",
] as const;

const mockupWorkbenchTextPairs = [
  ["activityBar.foreground", "activityBar.background"],
  ["activityBar.inactiveForeground", "activityBar.background"],
  ["activityBarBadge.foreground", "activityBarBadge.background"],
  ["badge.foreground", "badge.background"],
  ["button.foreground", "button.background"],
  ["button.secondaryForeground", "button.secondaryBackground"],
  ["checkbox.foreground", "checkbox.background"],
  ["commandCenter.activeForeground", "commandCenter.activeBackground"],
  ["commandCenter.foreground", "commandCenter.background"],
  ["dropdown.foreground", "dropdown.background"],
  ["editor.foreground", "editor.background"],
  ["editor.selectionForeground", "editor.selectionBackground"],
  ["editorLineNumber.foreground", "editor.background"],
  ["input.foreground", "input.background"],
  ["input.placeholderForeground", "input.background"],
  ["inputValidation.errorForeground", "inputValidation.errorBackground"],
  ["inputValidation.infoForeground", "inputValidation.infoBackground"],
  ["inputValidation.warningForeground", "inputValidation.warningBackground"],
  ["list.activeSelectionForeground", "list.activeSelectionBackground"],
  ["list.focusForeground", "list.focusBackground"],
  ["list.inactiveSelectionForeground", "list.inactiveSelectionBackground"],
  ["menu.foreground", "menu.background"],
  ["menu.selectionForeground", "menu.selectionBackground"],
  ["notifications.foreground", "notifications.background"],
  ["panelTitle.activeForeground", "panel.background"],
  ["panelTitle.inactiveForeground", "panel.background"],
  ["peekViewResult.selectionForeground", "peekViewResult.selectionBackground"],
  ["quickInput.foreground", "quickInput.background"],
  ["quickInputList.focusForeground", "quickInputList.focusBackground"],
  ["sideBar.foreground", "sideBar.background"],
  ["sideBarSectionHeader.foreground", "sideBarSectionHeader.background"],
  ["statusBar.foreground", "statusBar.background"],
  ["statusBar.debuggingForeground", "statusBar.debuggingBackground"],
  ["statusBarItem.errorForeground", "statusBarItem.errorBackground"],
  ["statusBarItem.remoteForeground", "statusBarItem.remoteBackground"],
  ["statusBarItem.warningForeground", "statusBarItem.warningBackground"],
  ["tab.activeForeground", "tab.activeBackground"],
  ["tab.inactiveForeground", "tab.inactiveBackground"],
  ["terminal.foreground", "terminal.background"],
  ["terminal.selectionForeground", "terminal.selectionBackground"],
  ["titleBar.activeForeground", "titleBar.activeBackground"],
  ["titleBar.inactiveForeground", "titleBar.inactiveBackground"],
] as const satisfies readonly ColorPair[];

const createMockupWorkbenchFeatureGroups = (C: Palette): FeatureGroup[] => {
  const B = C.background;
  const F = C.font;
  const pencil = B.guide;
  const ink = F.muted;
  const blueprint = F.sky;
  const redline = F.clay;
  const note = F.sand;

  return [
    ...createWorkbenchFeatureGroups(C),
    featureGroup("mockup.wireframe.all", keys(mockupBorderIds, pencil)),
    featureGroup("mockup.wireframe.focus", keys(mockupFocusBorderIds, blueprint)),
    featureGroup("mockup.wireframe.controls", keys(mockupControlBorderIds, ink)),
    featureGroup("mockup.wireframe.outer", keys(mockupOuterBorderIds, ink)),
    featureGroup("mockup.wireframe.validation", keys(mockupValidationBorderIds, redline)),
    featureGroup("mockup.wireframe.warning", keys(mockupWarningBorderIds, note)),
    featureGroup("mockup.wireframe.info", keys(mockupInfoBorderIds, blueprint)),
    featureGroup("workbench.shell", {
      "editor.lineHighlightBackground": withAlpha(B.sand, 0.28),
      foreground: F.text,
      disabledForeground: F.faint,
      descriptionForeground: F.faint,
      errorForeground: F.clay,
      "icon.foreground": F.muted,
      "selection.background": B.sand,
    }),
    featureGroup("editor.widgets", {
      "editorWidget.background": B.popup,
      "editorWidget.foreground": F.text,
      "editorHoverWidget.background": B.popup,
      "editorHoverWidget.foreground": F.text,
      "editorHoverWidget.statusBarBackground": B.panel,
    }),
    featureGroup("text.content", {
      "textBlockQuote.background": B.panel,
      "textSeparator.foreground": pencil,
      "textCodeBlock.background": B.popup,
      "textLink.activeForeground": F.sky,
      "textLink.foreground": F.sky,
      "textPreformat.background": B.popup,
      "textPreformat.foreground": F.text,
    }),
    featureGroup("toolbar.actions", {
      "toolbar.hoverBackground": B.hover,
      "toolbar.hoverOutline": blueprint,
      "toolbar.activeBackground": B.active,
      "actionBar.toggledBackground": B.sky,
    }),
    featureGroup("controls.form", {
      "button.background": B.sky,
      "button.foreground": F.text,
      "button.hoverBackground": B.info,
      "button.secondaryBackground": B.sand,
      "button.secondaryForeground": F.text,
      "button.secondaryHoverBackground": B.hover,
      "checkbox.background": B.popup,
      "checkbox.foreground": F.sky,
      "dropdown.background": B.popup,
      "dropdown.foreground": F.text,
      "dropdown.listBackground": B.popup,
      "input.background": B.popup,
      "input.foreground": F.text,
      "input.placeholderForeground": F.faint,
      "inputOption.activeBackground": B.sky,
      "inputOption.activeBorder": blueprint,
      "inputOption.activeForeground": F.text,
      "inputOption.hoverBackground": B.hover,
      "inputValidation.errorBackground": B.danger,
      "inputValidation.errorForeground": F.text,
      "inputValidation.infoBackground": B.info,
      "inputValidation.infoForeground": F.text,
      "inputValidation.warningBackground": B.accent,
      "inputValidation.warningForeground": F.text,
    }),
    featureGroup("progress.badges", {
      "badge.background": B.sky,
      "badge.foreground": F.text,
      "progressBar.background": F.sky,
    }),
    featureGroup("lists.trees", {
      "list.activeSelectionBackground": B.sky,
      "list.activeSelectionForeground": F.text,
      "list.dropBackground": B.info,
      "list.focusBackground": B.sky,
      "list.focusForeground": F.text,
      "list.focusOutline": blueprint,
      "list.highlightForeground": F.sky,
      "list.hoverBackground": B.hover,
      "list.inactiveFocusBackground": B.active,
      "list.inactiveSelectionBackground": B.active,
      "list.inactiveSelectionForeground": F.text,
    }),
    featureGroup("activity.bar", {
      "activityBar.background": B.panel,
      "activityBar.foreground": F.text,
      "activityBar.inactiveForeground": F.faint,
      "activityBar.activeBackground": B.active,
      "activityBar.activeBorder": blueprint,
      "activityBarBadge.background": B.clay,
      "activityBarBadge.foreground": F.text,
      "activityBarTop.background": B.panel,
      "activityBarTop.foreground": F.text,
      "activityBarTop.inactiveForeground": F.faint,
      "activityBarTop.activeBackground": B.active,
      "activityBarTop.activeBorder": blueprint,
    }),
    featureGroup("side.bar", {
      "sideBar.background": B.panel,
      "sideBar.foreground": F.text,
      "sideBarTitle.background": B.panel,
      "sideBarTitle.foreground": F.text,
      "sideBarSectionHeader.background": B.active,
      "sideBarSectionHeader.foreground": F.text,
      "sideBarStickyScroll.background": B.panel,
    }),
    featureGroup("tabs.groups", {
      "tab.activeBackground": B.editor,
      "tab.activeBorder": blueprint,
      "tab.activeBorderTop": ink,
      "tab.activeForeground": F.text,
      "tab.border": pencil,
      "tab.hoverBackground": B.hover,
      "tab.hoverForeground": F.text,
      "tab.inactiveBackground": B.panel,
      "tab.inactiveForeground": F.faint,
      "tab.unfocusedActiveForeground": F.text,
      "tab.unfocusedInactiveForeground": F.faint,
    }),
    featureGroup("editor.text", {
      "editor.foreground": F.text,
      "editorLineNumber.foreground": F.faint,
      "editorLineNumber.activeForeground": F.muted,
      "editorLineNumber.dimmedForeground": F.faint,
      "editorCursor.background": B.editor,
      "editorCursor.foreground": F.clay,
      "editor.selectionBackground": B.sky,
      "editor.selectionForeground": F.text,
      "editorWhitespace.foreground": B.guide,
      "editorIndentGuide.background1": B.guide,
      "editorIndentGuide.activeBackground1": F.faint,
      "editorRuler.foreground": B.guide,
      "editorCodeLens.foreground": F.faint,
      "editorLightBulb.foreground": F.ember,
      "editorLightBulbAutoFix.foreground": F.moss,
      "editorBracketMatch.background": B.sand,
      "editorBracketMatch.border": ink,
      "editorBracketHighlight.foreground1": F.muted,
      "editorBracketHighlight.foreground2": F.muted,
      "editorBracketHighlight.foreground3": F.muted,
      "editorBracketHighlight.foreground4": F.muted,
      "editorBracketHighlight.foreground5": F.muted,
      "editorBracketHighlight.foreground6": F.muted,
      "editorUnicodeHighlight.background": B.accent,
      "editorUnicodeHighlight.border": note,
      "editor.foldBackground": withAlpha(B.sand, 0.3),
      "editor.inlineValuesBackground": B.panel,
      "editor.inlineValuesForeground": F.muted,
    }),
    featureGroup("editor.diagnostics", {
      "editorGutter.addedBackground": B.moss,
      "editorGutter.deletedBackground": B.clay,
      "editorGutter.modifiedBackground": B.sky,
      "editorGutter.commentRangeForeground": F.faint,
      "editorOverviewRuler.addedForeground": F.moss,
      "editorOverviewRuler.deletedForeground": F.clay,
      "editorOverviewRuler.modifiedForeground": F.sky,
      "editorOverviewRuler.errorForeground": F.clay,
      "editorOverviewRuler.warningForeground": F.sand,
      "editorOverviewRuler.infoForeground": F.sky,
      "editorOverviewRuler.border": ink,
      "editorError.foreground": F.clay,
      "editorError.border": redline,
      "editorWarning.foreground": F.sand,
      "editorWarning.border": note,
      "editorInfo.foreground": F.sky,
      "editorInfo.border": blueprint,
      "editorHint.foreground": F.moss,
      "editorHint.border": blueprint,
      "problemsErrorIcon.foreground": F.clay,
      "problemsWarningIcon.foreground": F.sand,
      "problemsInfoIcon.foreground": F.sky,
    }),
    featureGroup("panel", {
      "panel.background": B.panel,
      "panel.border": ink,
      "panelTitle.activeBorder": blueprint,
      "panelTitle.activeForeground": F.text,
      "panelTitle.inactiveForeground": F.faint,
    }),
    featureGroup("terminal", {
      "terminal.foreground": F.text,
      "terminal.ansiBlack": F.muted,
      "terminal.ansiBlue": F.sky,
      "terminal.ansiBrightBlack": F.faint,
      "terminal.ansiBrightBlue": F.sky,
      "terminal.ansiBrightCyan": F.sky,
      "terminal.ansiBrightGreen": F.moss,
      "terminal.ansiBrightMagenta": F.plum,
      "terminal.ansiBrightRed": F.clay,
      "terminal.ansiBrightWhite": F.text,
      "terminal.ansiBrightYellow": F.sand,
      "terminal.ansiCyan": F.sky,
      "terminal.ansiGreen": F.moss,
      "terminal.ansiMagenta": F.plum,
      "terminal.ansiRed": F.clay,
      "terminal.ansiWhite": F.text,
      "terminal.ansiYellow": F.sand,
      "terminalCursor.background": B.editor,
      "terminalCursor.foreground": F.clay,
      "terminal.selectionBackground": B.sky,
      "terminal.selectionForeground": F.text,
      "terminal.border": ink,
    }),
    featureGroup("debug", {
      "debugToolBar.background": B.popup,
      "debugToolBar.border": ink,
      "debugIcon.continueForeground": F.moss,
      "debugIcon.disconnectForeground": F.clay,
      "debugIcon.pauseForeground": F.sand,
      "debugIcon.restartForeground": F.sky,
      "debugIcon.startForeground": F.moss,
      "debugIcon.stepBackForeground": F.sky,
      "debugIcon.stepIntoForeground": F.sky,
      "debugIcon.stepOutForeground": F.sky,
      "debugIcon.stepOverForeground": F.sky,
      "debugIcon.stopForeground": F.clay,
    }),
    featureGroup("status.bar", {
      "statusBar.background": B.panel,
      "statusBar.border": ink,
      "statusBar.foreground": F.muted,
      "statusBar.debuggingBackground": B.plum,
      "statusBar.debuggingForeground": F.text,
      "statusBar.noFolderBackground": B.panel,
      "statusBar.noFolderForeground": F.muted,
      "statusBarItem.activeBackground": B.active,
      "statusBarItem.hoverBackground": B.hover,
      "statusBarItem.prominentBackground": B.sky,
      "statusBarItem.prominentForeground": F.text,
      "statusBarItem.remoteBackground": B.sky,
      "statusBarItem.remoteForeground": F.text,
      "statusBarItem.errorBackground": B.clay,
      "statusBarItem.errorForeground": F.text,
      "statusBarItem.warningBackground": B.sand,
      "statusBarItem.warningForeground": F.text,
    }),
    featureGroup("title.bar", {
      "titleBar.activeBackground": B.panel,
      "titleBar.activeForeground": F.text,
      "titleBar.border": ink,
      "titleBar.inactiveBackground": B.editor,
      "titleBar.inactiveForeground": F.faint,
    }),
    featureGroup("menus", {
      "menu.background": B.popup,
      "menu.border": ink,
      "menu.foreground": F.text,
      "menu.selectionBackground": B.sky,
      "menu.selectionBorder": blueprint,
      "menu.selectionForeground": F.text,
      "menu.separatorBackground": pencil,
      "menubar.selectionBackground": B.sky,
      "menubar.selectionBorder": blueprint,
      "menubar.selectionForeground": F.text,
    }),
    featureGroup("command.center", {
      "commandCenter.foreground": F.muted,
      "commandCenter.activeForeground": F.text,
      "commandCenter.background": B.panel,
      "commandCenter.activeBackground": B.sky,
      "commandCenter.border": ink,
      "commandCenter.inactiveForeground": F.faint,
      "commandCenter.inactiveBorder": pencil,
      "commandCenter.activeBorder": blueprint,
      "commandCenter.debuggingBackground": withAlpha(B.plum, 0.88),
    }),
    featureGroup("notifications", {
      "notificationCenter.border": ink,
      "notificationCenterHeader.background": B.panel,
      "notificationCenterHeader.foreground": F.text,
      "notificationToast.border": ink,
      "notifications.background": B.popup,
      "notifications.border": ink,
      "notifications.foreground": F.text,
      "notificationsErrorIcon.foreground": F.clay,
      "notificationsInfoIcon.foreground": F.sky,
      "notificationsWarningIcon.foreground": F.sand,
    }),
    featureGroup("quick.input", {
      "quickInput.background": B.popup,
      "quickInput.foreground": F.text,
      "quickInputList.focusBackground": B.sky,
      "quickInputList.focusForeground": F.text,
      "quickInputTitle.background": B.panel,
      "pickerGroup.border": pencil,
      "pickerGroup.foreground": F.muted,
    }),
    featureGroup("settings", {
      "settings.checkboxBackground": B.popup,
      "settings.dropdownBackground": B.popup,
      "settings.headerForeground": F.text,
      "settings.modifiedItemIndicator": F.sand,
      "settings.numberInputBackground": B.popup,
      "settings.rowHoverBackground": B.hover,
      "settings.sashBorder": ink,
      "settings.textInputBackground": B.popup,
    }),
    featureGroup("breadcrumbs", {
      "breadcrumb.background": B.editor,
      "breadcrumb.focusForeground": F.text,
      "breadcrumb.foreground": F.faint,
      "breadcrumb.activeSelectionForeground": F.text,
      "breadcrumbPicker.background": B.popup,
    }),
    featureGroup("peek.view", {
      "peekViewResult.fileForeground": F.text,
      "peekViewResult.lineForeground": F.muted,
      "peekViewResult.selectionBackground": B.sky,
      "peekViewResult.selectionForeground": F.text,
      "peekView.border": ink,
      "peekViewTitle.background": B.popup,
      "peekViewTitleDescription.foreground": F.muted,
      "peekViewTitleLabel.foreground": F.text,
    }),
    featureGroup("git.decorations", {
      "gitDecoration.addedResourceForeground": F.moss,
      "gitDecoration.conflictingResourceForeground": F.sand,
      "gitDecoration.deletedResourceForeground": F.clay,
      "gitDecoration.ignoredResourceForeground": F.faint,
      "gitDecoration.modifiedResourceForeground": F.sky,
      "gitDecoration.renamedResourceForeground": F.moss,
      "gitDecoration.stageDeletedResourceForeground": F.clay,
      "gitDecoration.stageModifiedResourceForeground": F.sky,
      "gitDecoration.submoduleResourceForeground": F.sky,
      "gitDecoration.untrackedResourceForeground": F.moss,
    }),
    featureGroup("scm.graph", {
      "scmGraph.historyItemHoverLabelForeground": B.editor,
    }),
    featureGroup("charts", {
      "charts.blue": F.sky,
      "charts.foreground": F.text,
      "charts.green": F.moss,
      "charts.orange": F.ember,
      "charts.purple": F.plum,
      "charts.red": F.clay,
      "charts.yellow": F.sand,
      "charts.lines": pencil,
    }),
    featureGroup("testing", {
      "testing.iconErrored": F.clay,
      "testing.iconFailed": F.clay,
      "testing.iconPassed": F.moss,
      "testing.iconQueued": F.muted,
      "testing.iconSkipped": F.faint,
      "testing.iconUnset": F.faint,
    }),
    featureGroup("welcome.page", {
      "welcomePage.tileBackground": B.popup,
      "welcomePage.tileBorder": ink,
      "welcomePage.tileHoverBackground": B.hover,
    }),
  ];
};

export const theme = defineTheme({
  order: 30,
  fileName: "jacks-theme-mockup-color-theme.json",
  name: "Jack's Theme Mockup",
  type: "light",
  palette: MOCKUP_PALETTE,
  fontPalette: MOCKUP_FONT_COLORS,
  workbench: createMockupWorkbenchFeatureGroups(MOCKUP_PALETTE),
  integrity: {
    borderPolicy: {
      kind: "mapped",
      visibleIds: mockupBorderIds,
      requiredVisibleIds: mockupBorderIds,
    },
    workbenchTextPairs: mockupWorkbenchTextPairs,
  },
});
