import { keys } from "./colors.js";
import { featureGroup, mergeFeatureGroups } from "./theme.js";
import type { ColorPair, FeatureGroup, Theme } from "./theme.js";
import { borderColor } from "./workbench-styles.js";
import type {
  WorkbenchBorderStyles,
  WorkbenchStyles,
} from "./workbench-styles.js";

export const editorSurfaceIds = [
  "editor.background",
  "editorGutter.background",
  "editorGutter.itemBackground",
  "editorOverviewRuler.background",
  "editorStickyScroll.background",
  "editorStickyScrollGutter.background",
  "minimap.background",
  "notebook.cellEditorBackground",
  "notebook.editorBackground",
  "peekViewEditor.background",
  "peekViewEditorGutter.background",
  "peekViewEditorStickyScroll.background",
  "peekViewEditorStickyScrollGutter.background",
  "peekViewResult.background",
  "walkThrough.embeddedEditorBackground",
] as const;

// These surfaces appear below the editor's rendered line layer in VS Code's compositor.
export const editorUnderlayIds = [
  "editorGroup.emptyBackground",
  "editorGroupHeader.noTabsBackground",
  "editorGroupHeader.tabsBackground",
  "editorPane.background",
  "multiDiffEditor.background",
  "outputView.background",
  "terminal.background",
  "terminalStickyScroll.background",
  "welcomePage.background",
] as const;

const borderColorIdsByRole = {
  editorLineHighlight: ["editor.lineHighlightBorder"],
  editorRangeHighlight: ["editor.rangeHighlightBorder"],
  editorSelectionHighlight: ["editor.selectionHighlightBorder"],
  editorSymbolHighlight: ["editor.symbolHighlightBorder"],
  editorWordHighlight: ["editor.wordHighlightBorder"],
  editorWordHighlightStrong: ["editor.wordHighlightStrongBorder"],
  editorWordHighlightText: ["editor.wordHighlightTextBorder"],
  widget: [
    "widget.border",
    "editorWidget.border",
    "editorHoverWidget.border",
  ],
  widgetResize: ["editorWidget.resizeBorder"],
  window: ["window.activeBorder", "window.inactiveBorder"],
  contentDivider: ["textBlockQuote.border"],
  separator: ["textSeparator.foreground", "menu.separatorBackground"],
  control: [
    "button.border",
    "button.secondaryBorder",
    "checkbox.border",
    "dropdown.border",
    "input.border",
  ],
  validationError: ["inputValidation.errorBorder", "editorError.border"],
  validationWarning: ["inputValidation.warningBorder", "editorWarning.border"],
  validationInfo: [
    "inputValidation.infoBorder",
    "editorInfo.border",
    "editorHint.border",
  ],
  activityDivider: ["activityBar.border"],
  sidebarDivider: ["sideBar.border"],
  sidebarSection: ["sideBarSectionHeader.border"],
  editorGroup: ["editorGroup.border"],
  editorGroupHeader: [
    "editorGroupHeader.tabsBorder",
    "editorGroupHeader.border",
  ],
  tabDivider: ["tab.border"],
  findMatch: ["editor.findMatchBorder"],
  bracketMatch: ["editorBracketMatch.border"],
  unicodeHighlight: ["editorUnicodeHighlight.border"],
  diff: ["diffEditor.border"],
  panel: ["panel.border"],
  panelInput: ["panelInput.border"],
  terminal: ["terminal.border"],
  debugToolbar: ["debugToolBar.border"],
  statusBar: ["statusBar.border"],
  titleBar: ["titleBar.border"],
  menu: ["menu.border"],
  commandCenter: ["commandCenter.border"],
  notification: [
    "notificationCenter.border",
    "notificationToast.border",
    "notifications.border",
  ],
  picker: ["pickerGroup.border"],
  settingsControl: [
    "settings.checkboxBorder",
    "settings.dropdownBorder",
    "settings.numberInputBorder",
    "settings.textInputBorder",
  ],
  settingsSash: ["settings.sashBorder"],
  peek: ["peekView.border"],
  welcomeTile: ["welcomePage.tileBorder"],
  chartLine: ["charts.lines"],
} as const satisfies Record<keyof WorkbenchBorderStyles, readonly string[]>;

// These color IDs draw focus/selection outlines or scrollbar-adjacent chrome on
// top of the existing UI structure. They are intentionally not represented by
// WorkbenchBorderStyles: themes choose the structural border, if any, and these
// ignored border indicators always stay transparent to avoid adjacent
// double-border artifacts.
export const alwaysTransparentIgnoredBorderIds = [
  "focusBorder",
  "sash.hoverBorder",
  "toolbar.hoverOutline",
  "inputOption.activeBorder",
  "list.focusOutline",
  "activityBar.activeBorder",
  "activityBarTop.activeBorder",
  "tab.activeBorder",
  "tab.activeBorderTop",
  "panelTitle.activeBorder",
  "menu.selectionBorder",
  "menubar.selectionBorder",
  "commandCenter.inactiveBorder",
  "commandCenter.activeBorder",
  "editorOverviewRuler.border",
] as const;

export const getVisibleWorkbenchBorderColorIds = (
  styles: WorkbenchStyles,
): string[] =>
  (Object.keys(borderColorIdsByRole) as Array<keyof WorkbenchBorderStyles>)
    .filter((role) => styles.borders[role].kind === "visible")
    .flatMap((role) => [...borderColorIdsByRole[role]]);

export const workbenchTextPairs = [
  ["activityBar.foreground", "activityBar.background"],
  ["activityBar.inactiveForeground", "activityBar.background"],
  ["activityBarBadge.foreground", "activityBarBadge.background"],
  ["badge.foreground", "badge.background"],
  ["button.foreground", "button.background"],
  ["button.secondaryForeground", "button.secondaryBackground"],
  ["checkbox.foreground", "checkbox.background"],
  ["commandCenter.activeForeground", "commandCenter.activeBackground"],
  ["commandCenter.foreground", "commandCenter.background"],
  ["dropdown.foreground", "dropdown.background"],
  ["editor.foreground", "editor.background"],
  ["editor.selectionForeground", "editor.selectionBackground"],
  ["editorLineNumber.foreground", "editor.background"],
  ["input.foreground", "input.background"],
  ["input.placeholderForeground", "input.background"],
  ["inputValidation.errorForeground", "inputValidation.errorBackground"],
  ["inputValidation.infoForeground", "inputValidation.infoBackground"],
  ["inputValidation.warningForeground", "inputValidation.warningBackground"],
  ["list.activeSelectionForeground", "list.activeSelectionBackground"],
  ["list.focusForeground", "list.focusBackground"],
  ["list.inactiveSelectionForeground", "list.inactiveSelectionBackground"],
  ["menu.foreground", "menu.background"],
  ["menu.selectionForeground", "menu.selectionBackground"],
  ["notifications.foreground", "notifications.background"],
  ["panelTitle.activeForeground", "panel.background"],
  ["panelTitle.inactiveForeground", "panel.background"],
  ["peekViewResult.selectionForeground", "peekViewResult.selectionBackground"],
  ["quickInput.foreground", "quickInput.background"],
  ["quickInputList.focusForeground", "quickInputList.focusBackground"],
  ["sideBar.foreground", "sideBar.background"],
  ["sideBarSectionHeader.foreground", "sideBarSectionHeader.background"],
  ["statusBar.foreground", "statusBar.background"],
  ["statusBar.debuggingForeground", "statusBar.debuggingBackground"],
  ["statusBarItem.errorForeground", "statusBarItem.errorBackground"],
  ["statusBarItem.remoteForeground", "statusBarItem.remoteBackground"],
  ["statusBarItem.warningForeground", "statusBarItem.warningBackground"],
  ["tab.activeForeground", "tab.activeBackground"],
  ["tab.inactiveForeground", "tab.inactiveBackground"],
  ["terminal.foreground", "terminal.background"],
  ["terminal.selectionForeground", "terminal.selectionBackground"],
  ["titleBar.activeForeground", "titleBar.activeBackground"],
  ["titleBar.inactiveForeground", "titleBar.inactiveBackground"],
] as const satisfies readonly ColorPair[];

export const createWorkbenchFeatureGroups = (
  styles: WorkbenchStyles,
): FeatureGroup[] => {
  const S = styles.surfaces;
  const T = styles.text;
  const A = styles.accents;
  const O = styles.overlays;
  const R = styles.borders;
  const C = styles.controls;
  const L = styles.lists;
  const E = styles.editor;
  const transparent = styles.transparent;
  const border = borderColor;

  return [
    featureGroup("editor.surfaces", {
      ...keys(editorSurfaceIds, S.editor),
      ...keys(editorUnderlayIds, S.underlay),
      "editor.lineHighlightBorder": border(R.editorLineHighlight),
      "editor.rangeHighlightBorder": border(R.editorRangeHighlight),
      "editor.selectionHighlightBorder": border(R.editorSelectionHighlight),
      "editor.symbolHighlightBorder": border(R.editorSymbolHighlight),
      "editor.wordHighlightBorder": border(R.editorWordHighlight),
      "editor.wordHighlightStrongBorder": border(R.editorWordHighlightStrong),
      "editor.wordHighlightTextBorder": border(R.editorWordHighlightText),
      "scrollbar.background": transparent,
      "scrollbar.shadow": transparent,
    }),
    featureGroup("workbench.shell", {
      "editor.inactiveLineHighlightBackground": S.editor,
      "editor.lineHighlightBackground": O.lineHighlight,
      focusBorder: transparent,
      foreground: T.primary,
      disabledForeground: T.disabled,
      descriptionForeground: T.description,
      errorForeground: T.error,
      "icon.foreground": T.icon,
      "selection.background": A.selection,
      "sash.hoverBorder": transparent,
      "widget.border": border(R.widget),
      "widget.shadow": O.shadow,
    }),
    featureGroup("editor.widgets", {
      "editorWidget.background": S.popup,
      "editorWidget.border": border(R.widget),
      "editorWidget.foreground": T.primary,
      "editorWidget.resizeBorder": border(R.widgetResize),
      "editorHoverWidget.background": S.popup,
      "editorHoverWidget.border": border(R.widget),
      "editorHoverWidget.foreground": T.primary,
      "editorHoverWidget.statusBarBackground": S.panel,
    }),
    featureGroup("window.frame", {
      "window.activeBorder": border(R.window),
      "window.inactiveBorder": border(R.window),
    }),
    featureGroup("text.content", {
      "textBlockQuote.background": S.panel,
      "textBlockQuote.border": border(R.contentDivider),
      "textCodeBlock.background": S.popup,
      "textLink.activeForeground": T.link,
      "textLink.foreground": T.link,
      "textPreformat.background": S.popup,
      "textPreformat.foreground": T.primary,
      "textSeparator.foreground": border(R.separator),
    }),
    featureGroup("toolbar.actions", {
      "toolbar.hoverBackground": S.hover,
      "toolbar.hoverOutline": transparent,
      "toolbar.activeBackground": S.active,
      "actionBar.toggledBackground": A.toggled,
    }),
    featureGroup("controls.form", {
      "button.background": C.primaryButton.background,
      "button.border": border(R.control),
      "button.foreground": C.primaryButton.foreground,
      "button.hoverBackground": C.primaryButton.hoverBackground,
      "button.secondaryBackground": C.secondaryButton.background,
      "button.secondaryBorder": border(R.control),
      "button.secondaryForeground": C.secondaryButton.foreground,
      "button.secondaryHoverBackground": C.secondaryButton.hoverBackground,
      "checkbox.background": C.checkbox.background,
      "checkbox.border": border(R.control),
      "checkbox.foreground": C.checkbox.foreground,
      "dropdown.background": C.dropdown.background,
      "dropdown.border": border(R.control),
      "dropdown.foreground": C.dropdown.foreground,
      "dropdown.listBackground": C.dropdown.listBackground,
      "input.background": C.input.background,
      "input.border": border(R.control),
      "input.foreground": C.input.foreground,
      "input.placeholderForeground": C.input.placeholderForeground,
      "inputOption.activeBackground": C.inputOption.background,
      "inputOption.activeBorder": transparent,
      "inputOption.activeForeground": C.inputOption.foreground,
      "inputOption.hoverBackground": C.inputOption.hoverBackground,
      "inputValidation.errorBackground": C.validation.error.background,
      "inputValidation.errorBorder": border(R.validationError),
      "inputValidation.errorForeground": C.validation.error.foreground,
      "inputValidation.infoBackground": C.validation.info.background,
      "inputValidation.infoBorder": border(R.validationInfo),
      "inputValidation.infoForeground": C.validation.info.foreground,
      "inputValidation.warningBackground": C.validation.warning.background,
      "inputValidation.warningBorder": border(R.validationWarning),
      "inputValidation.warningForeground": C.validation.warning.foreground,
    }),
    featureGroup("progress.badges", {
      "badge.background": C.badge.background,
      "badge.foreground": C.badge.foreground,
      "progressBar.background": C.progress,
    }),
    featureGroup("lists.trees", {
      "list.activeSelectionBackground": L.activeSelection.background,
      "list.activeSelectionForeground": L.activeSelection.foreground,
      "list.dropBackground": L.dropBackground,
      "list.errorForeground": L.errorForeground,
      "list.focusBackground": L.focus.background,
      "list.focusForeground": L.focus.foreground,
      "list.focusOutline": transparent,
      "list.highlightForeground": L.highlightForeground,
      "list.hoverBackground": L.hoverBackground,
      "list.inactiveFocusBackground": L.inactiveFocusBackground,
      "list.inactiveSelectionBackground": L.inactiveSelection.background,
      "list.inactiveSelectionForeground": L.inactiveSelection.foreground,
      "list.invalidItemForeground": L.invalidItemForeground,
      "list.warningForeground": L.warningForeground,
    }),
    featureGroup("activity.bar", {
      "activityBar.background": S.activity,
      "activityBar.border": border(R.activityDivider),
      "activityBar.foreground": T.primary,
      "activityBar.inactiveForeground": T.faint,
      "activityBar.activeBackground": S.activityActive,
      "activityBar.activeBorder": transparent,
      "activityBarBadge.background": A.badge,
      "activityBarBadge.foreground": T.onAccent,
      "activityBarTop.background": S.activity,
      "activityBarTop.foreground": T.primary,
      "activityBarTop.inactiveForeground": T.faint,
      "activityBarTop.activeBackground": S.activityActive,
      "activityBarTop.activeBorder": transparent,
    }),
    featureGroup("side.bar", {
      "sideBar.background": S.sidebar,
      "sideBar.border": border(R.sidebarDivider),
      "sideBar.foreground": T.primary,
      "sideBarTitle.background": S.sidebar,
      "sideBarTitle.foreground": T.primary,
      "sideBarSectionHeader.background": S.sidebarSection,
      "sideBarSectionHeader.border": border(R.sidebarSection),
      "sideBarSectionHeader.foreground": T.primary,
      "sideBarStickyScroll.background": S.sidebar,
    }),
    featureGroup("tabs.groups", {
      "editorGroup.border": border(R.editorGroup),
      "editorGroup.dropBackground": A.info,
      "editorGroupHeader.tabsBorder": border(R.editorGroupHeader),
      "editorGroupHeader.border": border(R.editorGroupHeader),
      "tab.activeBackground": S.tabActive,
      "tab.activeBorder": transparent,
      "tab.activeBorderTop": transparent,
      "tab.activeForeground": T.primary,
      "tab.border": border(R.tabDivider),
      "tab.hoverBackground": S.hover,
      "tab.hoverForeground": T.primary,
      "tab.inactiveBackground": S.tabInactive,
      "tab.inactiveForeground": T.faint,
      "tab.unfocusedActiveForeground": T.primary,
      "tab.unfocusedInactiveForeground": T.faint,
    }),
    featureGroup("editor.text", {
      "editor.foreground": E.foreground,
      "editorLineNumber.foreground": E.lineNumber,
      "editorLineNumber.activeForeground": E.activeLineNumber,
      "editorLineNumber.dimmedForeground": E.dimmedLineNumber,
      "editorCursor.background": E.cursorBackground,
      "editorCursor.foreground": E.cursorForeground,
      "editor.selectionBackground": E.selection.background,
      "editor.selectionForeground": E.selection.foreground,
      "editor.selectionHighlightBackground": O.subtle,
      "editor.inactiveSelectionBackground": O.subtle,
      "editor.wordHighlightBackground": O.wordHighlight,
      "editor.wordHighlightStrongBackground": O.wordHighlightStrong,
      "editor.wordHighlightTextBackground": O.wordHighlightText,
      "editor.findMatchBackground": O.searchMatch,
      "editor.findMatchBorder": border(R.findMatch),
      "editor.findMatchHighlightBackground": O.searchHighlight,
      "editor.findRangeHighlightBackground": O.medium,
      "editor.hoverHighlightBackground": O.subtle,
      "editor.linkedEditingBackground": S.active,
      "editor.rangeHighlightBackground": O.subtle,
      "editor.symbolHighlightBackground": O.medium,
      "editorWhitespace.foreground": E.whitespaceForeground,
      "editorIndentGuide.background1": E.indentGuide,
      "editorIndentGuide.activeBackground1": E.activeIndentGuide,
      "editorRuler.foreground": E.rulerForeground,
      "editorCodeLens.foreground": E.codeLensForeground,
      "editorLightBulb.foreground": E.lightBulbForeground,
      "editorLightBulbAutoFix.foreground": E.lightBulbAutoFixForeground,
      "editorBracketMatch.background": E.bracketMatchBackground,
      "editorBracketMatch.border": border(R.bracketMatch),
      "editorBracketHighlight.foreground1": E.bracketHighlightForeground,
      "editorBracketHighlight.foreground2": E.bracketHighlightForeground,
      "editorBracketHighlight.foreground3": E.bracketHighlightForeground,
      "editorBracketHighlight.foreground4": E.bracketHighlightForeground,
      "editorBracketHighlight.foreground5": E.bracketHighlightForeground,
      "editorBracketHighlight.foreground6": E.bracketHighlightForeground,
      "editorBracketHighlight.unexpectedBracket.foreground":
        E.unexpectedBracketForeground,
      "editorBracketPairGuide.background1": E.indentGuide,
      "editorBracketPairGuide.activeBackground1": E.activeIndentGuide,
      "editorUnicodeHighlight.border": border(R.unicodeHighlight),
      "editorUnicodeHighlight.background": E.unicodeHighlightBackground,
      "editor.foldBackground": O.fold,
      "editor.inlineValuesBackground": E.inlineValues.background,
      "editor.inlineValuesForeground": E.inlineValues.foreground,
    }),
    featureGroup("editor.diagnostics", {
      "editorGutter.addedBackground": A.success,
      "editorGutter.deletedBackground": A.danger,
      "editorGutter.modifiedBackground": A.primary,
      "editorGutter.commentRangeForeground": T.faint,
      "editorOverviewRuler.addedForeground": T.success,
      "editorOverviewRuler.deletedForeground": T.error,
      "editorOverviewRuler.modifiedForeground": T.info,
      "editorOverviewRuler.border": transparent,
      "editorOverviewRuler.errorForeground": T.error,
      "editorOverviewRuler.warningForeground": T.warning,
      "editorOverviewRuler.infoForeground": T.info,
      "editorOverviewRuler.findMatchForeground": O.searchHighlight,
      "editorOverviewRuler.rangeHighlightForeground": O.subtle,
      "editorOverviewRuler.selectionHighlightForeground": O.selection,
      "editorOverviewRuler.wordHighlightForeground": O.wordHighlight,
      "editorOverviewRuler.wordHighlightStrongForeground": O.wordHighlightStrong,
      "editorError.foreground": T.error,
      "editorError.border": border(R.validationError),
      "editorError.background": transparent,
      "editorWarning.foreground": T.warning,
      "editorWarning.border": border(R.validationWarning),
      "editorWarning.background": transparent,
      "editorInfo.foreground": T.info,
      "editorInfo.border": border(R.validationInfo),
      "editorInfo.background": transparent,
      "editorHint.foreground": T.success,
      "editorHint.border": border(R.validationInfo),
      "problemsErrorIcon.foreground": T.error,
      "problemsWarningIcon.foreground": T.warning,
      "problemsInfoIcon.foreground": T.info,
    }),
    featureGroup("diff.editor", {
      "diffEditor.insertedTextBackground": O.diffInsertedText,
      "diffEditor.insertedLineBackground": O.diffInsertedLine,
      "diffEditor.removedTextBackground": O.diffRemovedText,
      "diffEditor.removedLineBackground": O.diffRemovedLine,
      "diffEditorGutter.insertedLineBackground": transparent,
      "diffEditorGutter.removedLineBackground": transparent,
      "diffEditor.border": border(R.diff),
      "diffEditor.diagonalFill": S.guide,
      "diffEditor.unchangedRegionBackground": S.panel,
      "diffEditor.unchangedRegionForeground": T.faint,
      "diffEditor.unchangedCodeBackground": S.editor,
    }),
    featureGroup("panel", {
      "panel.background": S.panelArea,
      "panel.border": border(R.panel),
      "panelTitle.activeBorder": transparent,
      "panelTitle.activeForeground": T.primary,
      "panelTitle.inactiveForeground": T.faint,
      "panelInput.border": border(R.panelInput),
    }),
    featureGroup("terminal", {
      "terminal.foreground": T.primary,
      "terminal.ansiBlack": T.faint,
      "terminal.ansiBlue": T.info,
      "terminal.ansiBrightBlack": T.faint,
      "terminal.ansiBrightBlue": T.info,
      "terminal.ansiBrightCyan": T.info,
      "terminal.ansiBrightGreen": T.success,
      "terminal.ansiBrightMagenta": T.plum,
      "terminal.ansiBrightRed": T.error,
      "terminal.ansiBrightWhite": T.primary,
      "terminal.ansiBrightYellow": T.warning,
      "terminal.ansiCyan": T.info,
      "terminal.ansiGreen": T.success,
      "terminal.ansiMagenta": T.plum,
      "terminal.ansiRed": T.error,
      "terminal.ansiWhite": T.primary,
      "terminal.ansiYellow": T.warning,
      "terminal.border": border(R.terminal),
      "terminalCursor.background": E.cursorBackground,
      "terminalCursor.foreground": E.cursorForeground,
      "terminal.selectionBackground": A.selection,
      "terminal.selectionForeground": T.onAccent,
    }),
    featureGroup("debug", {
      "debugToolBar.background": S.popup,
      "debugToolBar.border": border(R.debugToolbar),
      "debugIcon.continueForeground": T.success,
      "debugIcon.disconnectForeground": T.error,
      "debugIcon.pauseForeground": T.warning,
      "debugIcon.restartForeground": T.info,
      "debugIcon.startForeground": T.success,
      "debugIcon.stepBackForeground": T.info,
      "debugIcon.stepIntoForeground": T.info,
      "debugIcon.stepOutForeground": T.info,
      "debugIcon.stepOverForeground": T.info,
      "debugIcon.stopForeground": T.error,
    }),
    featureGroup("status.bar", {
      "statusBar.background": S.statusBar,
      "statusBar.border": border(R.statusBar),
      "statusBar.foreground": T.muted,
      "statusBar.debuggingBackground": A.debug,
      "statusBar.debuggingForeground": T.onAccent,
      "statusBar.noFolderBackground": S.statusBar,
      "statusBar.noFolderForeground": T.muted,
      "statusBarItem.activeBackground": S.active,
      "statusBarItem.hoverBackground": S.hover,
      "statusBarItem.prominentBackground": A.prominent,
      "statusBarItem.prominentForeground": T.onAccent,
      "statusBarItem.remoteBackground": A.primary,
      "statusBarItem.remoteForeground": T.onAccent,
      "statusBarItem.errorBackground": A.danger,
      "statusBarItem.errorForeground": T.onAccent,
      "statusBarItem.warningBackground": A.warning,
      "statusBarItem.warningForeground": T.onAccent,
    }),
    featureGroup("title.bar", {
      "titleBar.activeBackground": S.titleBar,
      "titleBar.activeForeground": T.primary,
      "titleBar.border": border(R.titleBar),
      "titleBar.inactiveBackground": S.titleBarInactive,
      "titleBar.inactiveForeground": T.faint,
    }),
    featureGroup("menus", {
      "menu.background": S.popup,
      "menu.border": border(R.menu),
      "menu.foreground": T.primary,
      "menu.selectionBackground": S.menuSelection,
      "menu.selectionBorder": transparent,
      "menu.selectionForeground": T.primary,
      "menu.separatorBackground": border(R.separator),
      "menubar.selectionBackground": S.menuSelection,
      "menubar.selectionBorder": transparent,
      "menubar.selectionForeground": T.primary,
    }),
    featureGroup("command.center", {
      "commandCenter.foreground": T.muted,
      "commandCenter.activeForeground": T.primary,
      "commandCenter.background": S.commandCenter,
      "commandCenter.activeBackground": S.commandCenterActive,
      "commandCenter.border": border(R.commandCenter),
      "commandCenter.inactiveForeground": T.faint,
      "commandCenter.inactiveBorder": transparent,
      "commandCenter.activeBorder": transparent,
      "commandCenter.debuggingBackground": O.commandDebugging,
    }),
    featureGroup("notifications", {
      "notificationCenter.border": border(R.notification),
      "notificationCenterHeader.background": S.notificationHeader,
      "notificationCenterHeader.foreground": T.primary,
      "notificationToast.border": border(R.notification),
      "notifications.background": S.popup,
      "notifications.border": border(R.notification),
      "notifications.foreground": T.primary,
      "notificationsErrorIcon.foreground": T.error,
      "notificationsInfoIcon.foreground": T.info,
      "notificationsWarningIcon.foreground": T.warning,
    }),
    featureGroup("quick.input", {
      "quickInput.background": S.popup,
      "quickInput.foreground": T.primary,
      "quickInputList.focusBackground": L.focus.background,
      "quickInputList.focusForeground": L.focus.foreground,
      "quickInputTitle.background": S.quickInputTitle,
      "pickerGroup.border": border(R.picker),
      "pickerGroup.foreground": T.muted,
    }),
    featureGroup("settings", {
      "settings.checkboxBackground": S.settingsInput,
      "settings.checkboxBorder": border(R.settingsControl),
      "settings.dropdownBackground": S.settingsInput,
      "settings.dropdownBorder": border(R.settingsControl),
      "settings.headerForeground": T.primary,
      "settings.modifiedItemIndicator": T.warning,
      "settings.numberInputBackground": S.settingsInput,
      "settings.numberInputBorder": border(R.settingsControl),
      "settings.rowHoverBackground": S.hover,
      "settings.sashBorder": border(R.settingsSash),
      "settings.textInputBackground": S.settingsInput,
      "settings.textInputBorder": border(R.settingsControl),
    }),
    featureGroup("breadcrumbs", {
      "breadcrumb.background": S.editor,
      "breadcrumb.focusForeground": T.primary,
      "breadcrumb.foreground": T.faint,
      "breadcrumb.activeSelectionForeground": T.primary,
      "breadcrumbPicker.background": S.popup,
    }),
    featureGroup("peek.view", {
      "peekView.border": border(R.peek),
      "peekViewEditor.matchHighlightBackground": O.searchMatch,
      "peekViewResult.fileForeground": T.primary,
      "peekViewResult.lineForeground": T.muted,
      "peekViewResult.matchHighlightBackground": O.searchMatch,
      "peekViewResult.selectionBackground": L.activeSelection.background,
      "peekViewResult.selectionForeground": L.activeSelection.foreground,
      "peekViewTitle.background": S.popup,
      "peekViewTitleDescription.foreground": T.muted,
      "peekViewTitleLabel.foreground": T.primary,
    }),
    featureGroup("git.decorations", {
      "gitDecoration.addedResourceForeground": T.success,
      "gitDecoration.conflictingResourceForeground": T.warning,
      "gitDecoration.deletedResourceForeground": T.error,
      "gitDecoration.ignoredResourceForeground": T.faint,
      "gitDecoration.modifiedResourceForeground": T.info,
      "gitDecoration.renamedResourceForeground": T.success,
      "gitDecoration.stageDeletedResourceForeground": T.error,
      "gitDecoration.stageModifiedResourceForeground": T.info,
      "gitDecoration.submoduleResourceForeground": T.info,
      "gitDecoration.untrackedResourceForeground": T.success,
    }),
    featureGroup("scm.graph", {
      "scmGraph.foreground1": T.warning,
      "scmGraph.foreground2": T.error,
      "scmGraph.foreground3": T.ember,
      "scmGraph.foreground4": T.success,
      "scmGraph.foreground5": T.plum,
      "scmGraph.historyItemBaseRefColor": T.ember,
      "scmGraph.historyItemHoverAdditionsForeground": T.success,
      "scmGraph.historyItemHoverDefaultLabelBackground": S.active,
      "scmGraph.historyItemHoverDefaultLabelForeground": T.primary,
      "scmGraph.historyItemHoverDeletionsForeground": T.error,
      "scmGraph.historyItemHoverLabelForeground": S.editor,
      "scmGraph.historyItemRefColor": T.info,
      "scmGraph.historyItemRemoteRefColor": T.plum,
    }),
    featureGroup("minimap", {
      "minimap.findMatchHighlight": O.searchHighlight,
      "minimap.selectionHighlight": O.selection,
      "minimap.errorHighlight": T.error,
      "minimap.warningHighlight": T.warning,
      "minimap.infoHighlight": T.info,
      "minimap.foregroundOpacity": O.minimapOpacity,
      "minimapGutter.addedBackground": A.success,
      "minimapGutter.deletedBackground": A.danger,
      "minimapGutter.modifiedBackground": A.primary,
      "minimapSlider.activeBackground": T.muted,
      "minimapSlider.background": S.guide,
      "minimapSlider.hoverBackground": T.faint,
    }),
    featureGroup("scrollbars", {
      "scrollbarSlider.activeBackground": O.scrollbarActive,
      "scrollbarSlider.background": O.scrollbar,
      "scrollbarSlider.hoverBackground": O.scrollbarHover,
    }),
    featureGroup("charts", {
      "charts.blue": T.info,
      "charts.foreground": T.primary,
      "charts.green": T.success,
      "charts.lines": border(R.chartLine),
      "charts.orange": T.ember,
      "charts.purple": T.plum,
      "charts.red": T.error,
      "charts.yellow": T.warning,
    }),
    featureGroup("testing", {
      "testing.iconErrored": T.error,
      "testing.iconFailed": T.error,
      "testing.iconPassed": T.success,
      "testing.iconQueued": T.muted,
      "testing.iconSkipped": T.faint,
      "testing.iconUnset": T.faint,
    }),
    featureGroup("welcome.page", {
      "welcomePage.tileBackground": S.welcomeTile,
      "welcomePage.tileHoverBackground": S.hover,
      "welcomePage.tileBorder": border(R.welcomeTile),
    }),
  ];
};

export const createWorkbenchColors = (
  styles: WorkbenchStyles,
): Theme["colors"] => mergeFeatureGroups(createWorkbenchFeatureGroups(styles));
