import { keys, withAlpha } from "./colors.js";
import { featureGroup, mergeFeatureGroups } from "./theme.js";
import type { FeatureGroup, Palette, Theme } from "./theme.js";

export const editorSurfaceIds = [
  "editor.background",
  "editorGutter.background",
  "editorGutter.itemBackground",
  "editorOverviewRuler.background",
  "editorStickyScroll.background",
  "editorStickyScrollGutter.background",
  "minimap.background",
  "notebook.cellEditorBackground",
  "notebook.editorBackground",
  "peekViewEditor.background",
  "peekViewEditorGutter.background",
  "peekViewEditorStickyScroll.background",
  "peekViewEditorStickyScrollGutter.background",
  "peekViewResult.background",
  "walkThrough.embeddedEditorBackground",
] as const;

// These surfaces appear below the editor's rendered line layer in VS Code's compositor.
export const editorUnderlayIds = [
  "editorGroup.emptyBackground",
  "editorGroupHeader.noTabsBackground",
  "editorGroupHeader.tabsBackground",
  "editorPane.background",
  "multiDiffEditor.background",
  "outputView.background",
  "terminal.background",
  "terminalStickyScroll.background",
  "welcomePage.background",
] as const;

const transparentEditorOverlayIds = [
  "editor.lineHighlightBorder",
  "editor.rangeHighlightBorder",
  "editor.selectionHighlightBorder",
  "editor.symbolHighlightBorder",
  "editor.wordHighlightBorder",
  "editor.wordHighlightStrongBorder",
  "editor.wordHighlightTextBorder",
  "scrollbar.background",
  "scrollbar.shadow",
] as const;

export const createWorkbenchFeatureGroups = (C: Palette): FeatureGroup[] => {
  const B = C.background;
  const F = C.font;
  const subtle = withAlpha(B.hover, 0.72);
  const medium = withAlpha(B.active, 0.72);
  const selectionHighlight = withAlpha(B.sky, 0.76);
  const searchHighlight = withAlpha(B.mark, 0.72);
  const searchMatch = withAlpha(B.mark, 0.82);
  const lineHighlight = withAlpha(B.mark, 0.24);
  const wordHighlight = withAlpha(B.mark, 0.72);
  const wordHighlightStrong = withAlpha(B.mark, 0.78);
  const wordHighlightText = withAlpha(B.mark, 0.7);
  const diffLineSuccess = withAlpha(B.success, 0.44);
  const diffLineDanger = withAlpha(B.danger, 0.44);
  const diffTextSuccess = withAlpha(B.success, 0.58);
  const diffTextDanger = withAlpha(B.danger, 0.58);

  return [
    featureGroup("editor.surfaces", {
      ...keys(editorSurfaceIds, B.editor),
      ...keys(editorUnderlayIds, B.editor),
      ...keys(transparentEditorOverlayIds, B.transparent),
    }),
    featureGroup("workbench.shell", {
      "editor.inactiveLineHighlightBackground": B.editor,
      "editor.lineHighlightBackground": lineHighlight,
      focusBorder: B.transparent,
      foreground: F.text,
      disabledForeground: F.faint,
      descriptionForeground: F.muted,
      errorForeground: F.clay,
      "icon.foreground": F.muted,
      "selection.background": B.sky,
      "sash.hoverBorder": B.transparent,
      "widget.border": B.transparent,
      "widget.shadow": B.shadow,
    }),
    featureGroup("editor.widgets", {
      "editorWidget.background": B.popup,
      "editorWidget.border": B.transparent,
      "editorWidget.foreground": F.text,
      "editorWidget.resizeBorder": B.transparent,
      "editorHoverWidget.background": B.popup,
      "editorHoverWidget.border": B.transparent,
      "editorHoverWidget.foreground": F.text,
      "editorHoverWidget.statusBarBackground": B.panel,
    }),
    featureGroup("window.frame", {
      "window.activeBorder": B.transparent,
      "window.inactiveBorder": B.transparent,
    }),
    featureGroup("text.content", {
      "textBlockQuote.background": B.panel,
      "textBlockQuote.border": B.transparent,
      "textCodeBlock.background": B.popup,
      "textLink.activeForeground": F.sky,
      "textLink.foreground": F.sky,
      "textPreformat.background": B.popup,
      "textPreformat.foreground": F.text,
      "textSeparator.foreground": B.transparent,
    }),
    featureGroup("toolbar.actions", {
      "toolbar.hoverBackground": B.hover,
      "toolbar.hoverOutline": B.transparent,
      "toolbar.activeBackground": B.active,
      "actionBar.toggledBackground": B.active,
    }),
    featureGroup("controls.form", {
      "button.background": B.sky,
      "button.border": B.transparent,
      "button.foreground": F.text,
      "button.hoverBackground": B.sky,
      "button.secondaryBackground": B.active,
      "button.secondaryBorder": B.transparent,
      "button.secondaryForeground": F.text,
      "button.secondaryHoverBackground": B.hover,
      "checkbox.background": B.panel,
      "checkbox.border": B.transparent,
      "checkbox.foreground": F.sky,
      "dropdown.background": B.popup,
      "dropdown.border": B.transparent,
      "dropdown.foreground": F.text,
      "dropdown.listBackground": B.popup,
      "input.background": B.panel,
      "input.border": B.transparent,
      "input.foreground": F.text,
      "input.placeholderForeground": F.faint,
      "inputOption.activeBackground": B.active,
      "inputOption.activeBorder": B.transparent,
      "inputOption.activeForeground": F.text,
      "inputOption.hoverBackground": B.hover,
      "inputValidation.errorBackground": B.danger,
      "inputValidation.errorBorder": B.transparent,
      "inputValidation.infoBackground": B.info,
      "inputValidation.infoBorder": B.transparent,
      "inputValidation.warningBackground": B.accent,
      "inputValidation.warningBorder": B.transparent,
    }),
    featureGroup("progress.badges", {
      "badge.background": B.active,
      "badge.foreground": F.text,
      "progressBar.background": B.sky,
    }),
    featureGroup("lists.trees", {
      "list.activeSelectionBackground": B.active,
      "list.activeSelectionForeground": F.text,
      "list.dropBackground": B.info,
      "list.errorForeground": F.clay,
      "list.focusBackground": B.active,
      "list.focusForeground": F.text,
      "list.highlightForeground": F.sky,
      "list.hoverBackground": B.hover,
      "list.inactiveFocusBackground": B.active,
      "list.inactiveSelectionBackground": B.active,
      "list.invalidItemForeground": F.clay,
      "list.warningForeground": F.sand,
    }),
    featureGroup("activity.bar", {
      "activityBar.background": B.editor,
      "activityBar.border": B.transparent,
      "activityBar.foreground": F.text,
      "activityBar.inactiveForeground": F.faint,
      "activityBar.activeBackground": B.hover,
      "activityBar.activeBorder": B.transparent,
      "activityBarBadge.background": B.sky,
      "activityBarBadge.foreground": F.text,
      "activityBarTop.background": B.editor,
      "activityBarTop.foreground": F.text,
      "activityBarTop.inactiveForeground": F.faint,
      "activityBarTop.activeBackground": B.hover,
      "activityBarTop.activeBorder": B.transparent,
    }),
    featureGroup("side.bar", {
      "sideBar.background": B.editor,
      "sideBar.border": B.transparent,
      "sideBar.foreground": F.text,
      "sideBarTitle.background": B.editor,
      "sideBarTitle.foreground": F.text,
      "sideBarSectionHeader.background": B.panel,
      "sideBarSectionHeader.border": B.transparent,
      "sideBarSectionHeader.foreground": F.text,
      "sideBarStickyScroll.background": B.editor,
    }),
    featureGroup("tabs.groups", {
      "editorGroup.border": B.transparent,
      "editorGroup.dropBackground": B.info,
      "editorGroupHeader.tabsBorder": B.transparent,
      "editorGroupHeader.border": B.transparent,
      "tab.activeBackground": B.editor,
      "tab.activeBorder": B.transparent,
      "tab.activeBorderTop": B.transparent,
      "tab.activeForeground": F.text,
      "tab.border": B.transparent,
      "tab.hoverBackground": B.hover,
      "tab.hoverForeground": F.text,
      "tab.inactiveBackground": B.editor,
      "tab.inactiveForeground": F.faint,
      "tab.unfocusedActiveForeground": F.text,
      "tab.unfocusedInactiveForeground": F.faint,
    }),
    featureGroup("editor.text", {
      "editor.foreground": F.text,
      "editorLineNumber.foreground": F.faint,
      "editorLineNumber.activeForeground": F.muted,
      "editorLineNumber.dimmedForeground": F.faint,
      "editorCursor.background": B.editor,
      "editorCursor.foreground": F.sky,
      "editor.selectionBackground": B.sky,
      "editor.selectionForeground": F.text,
      "editor.selectionHighlightBackground": subtle,
      "editor.inactiveSelectionBackground": subtle,
      "editor.wordHighlightBackground": wordHighlight,
      "editor.wordHighlightStrongBackground": wordHighlightStrong,
      "editor.wordHighlightTextBackground": wordHighlightText,
      "editor.findMatchBackground": searchMatch,
      "editor.findMatchBorder": B.transparent,
      "editor.findMatchHighlightBackground": searchHighlight,
      "editor.findRangeHighlightBackground": medium,
      "editor.hoverHighlightBackground": subtle,
      "editor.linkedEditingBackground": B.active,
      "editor.rangeHighlightBackground": subtle,
      "editor.symbolHighlightBackground": medium,
      "editorWhitespace.foreground": B.guide,
      "editorIndentGuide.background1": B.guide,
      "editorIndentGuide.activeBackground1": F.faint,
      "editorRuler.foreground": B.guide,
      "editorCodeLens.foreground": F.faint,
      "editorLightBulb.foreground": F.ember,
      "editorLightBulbAutoFix.foreground": F.moss,
      "editorBracketMatch.background": B.active,
      "editorBracketMatch.border": B.transparent,
      "editorBracketHighlight.foreground1": F.muted,
      "editorBracketHighlight.foreground2": F.muted,
      "editorBracketHighlight.foreground3": F.muted,
      "editorBracketHighlight.foreground4": F.muted,
      "editorBracketHighlight.foreground5": F.muted,
      "editorBracketHighlight.foreground6": F.muted,
      "editorBracketHighlight.unexpectedBracket.foreground": F.clay,
      "editorBracketPairGuide.background1": B.guide,
      "editorBracketPairGuide.activeBackground1": F.faint,
      "editorUnicodeHighlight.border": B.transparent,
      "editorUnicodeHighlight.background": B.accent,
      "editor.foldBackground": withAlpha(B.editor, 0.72),
      "editor.inlineValuesBackground": B.editor,
      "editor.inlineValuesForeground": F.muted,
    }),
    featureGroup("editor.diagnostics", {
      "editorGutter.addedBackground": B.moss,
      "editorGutter.deletedBackground": B.clay,
      "editorGutter.modifiedBackground": B.sky,
      "editorGutter.commentRangeForeground": F.faint,
      "editorOverviewRuler.addedForeground": F.moss,
      "editorOverviewRuler.deletedForeground": F.clay,
      "editorOverviewRuler.modifiedForeground": F.sky,
      "editorOverviewRuler.border": B.transparent,
      "editorOverviewRuler.errorForeground": F.clay,
      "editorOverviewRuler.warningForeground": F.sand,
      "editorOverviewRuler.infoForeground": F.sky,
      "editorOverviewRuler.findMatchForeground": searchHighlight,
      "editorOverviewRuler.rangeHighlightForeground": subtle,
      "editorOverviewRuler.selectionHighlightForeground": selectionHighlight,
      "editorOverviewRuler.wordHighlightForeground": wordHighlight,
      "editorOverviewRuler.wordHighlightStrongForeground": wordHighlightStrong,
      "editorError.foreground": F.clay,
      "editorError.border": B.transparent,
      "editorError.background": B.transparent,
      "editorWarning.foreground": F.sand,
      "editorWarning.border": B.transparent,
      "editorWarning.background": B.transparent,
      "editorInfo.foreground": F.sky,
      "editorInfo.border": B.transparent,
      "editorInfo.background": B.transparent,
      "editorHint.foreground": F.moss,
      "editorHint.border": B.transparent,
      "problemsErrorIcon.foreground": F.clay,
      "problemsWarningIcon.foreground": F.sand,
      "problemsInfoIcon.foreground": F.sky,
    }),
    featureGroup("diff.editor", {
      "diffEditor.insertedTextBackground": diffTextSuccess,
      "diffEditor.insertedLineBackground": diffLineSuccess,
      "diffEditor.removedTextBackground": diffTextDanger,
      "diffEditor.removedLineBackground": diffLineDanger,
      "diffEditorGutter.insertedLineBackground": B.transparent,
      "diffEditorGutter.removedLineBackground": B.transparent,
      "diffEditor.border": B.transparent,
      "diffEditor.diagonalFill": B.guide,
      "diffEditor.unchangedRegionBackground": B.panel,
      "diffEditor.unchangedRegionForeground": F.faint,
      "diffEditor.unchangedCodeBackground": B.editor,
    }),
    featureGroup("panel", {
      "panel.background": B.editor,
      "panel.border": B.transparent,
      "panelTitle.activeBorder": B.transparent,
      "panelTitle.activeForeground": F.text,
      "panelTitle.inactiveForeground": F.faint,
      "panelInput.border": B.transparent,
    }),
    featureGroup("terminal", {
      "terminal.foreground": F.text,
      "terminal.ansiBlack": F.faint,
      "terminal.ansiBlue": F.sky,
      "terminal.ansiBrightBlack": F.faint,
      "terminal.ansiBrightBlue": F.sky,
      "terminal.ansiBrightCyan": F.sky,
      "terminal.ansiBrightGreen": F.moss,
      "terminal.ansiBrightMagenta": F.plum,
      "terminal.ansiBrightRed": F.clay,
      "terminal.ansiBrightWhite": F.text,
      "terminal.ansiBrightYellow": F.sand,
      "terminal.ansiCyan": F.sky,
      "terminal.ansiGreen": F.moss,
      "terminal.ansiMagenta": F.plum,
      "terminal.ansiRed": F.clay,
      "terminal.ansiWhite": F.text,
      "terminal.ansiYellow": F.sand,
      "terminal.border": B.transparent,
      "terminalCursor.background": B.editor,
      "terminalCursor.foreground": F.sky,
      "terminal.selectionBackground": B.sky,
    }),
    featureGroup("debug", {
      "debugToolBar.background": B.popup,
      "debugToolBar.border": B.transparent,
      "debugIcon.continueForeground": F.moss,
      "debugIcon.disconnectForeground": F.clay,
      "debugIcon.pauseForeground": F.sand,
      "debugIcon.restartForeground": F.sky,
      "debugIcon.startForeground": F.moss,
      "debugIcon.stepBackForeground": F.sky,
      "debugIcon.stepIntoForeground": F.sky,
      "debugIcon.stepOutForeground": F.sky,
      "debugIcon.stepOverForeground": F.sky,
      "debugIcon.stopForeground": F.clay,
    }),
    featureGroup("status.bar", {
      "statusBar.background": B.editor,
      "statusBar.border": B.transparent,
      "statusBar.foreground": F.muted,
      "statusBar.debuggingBackground": B.plum,
      "statusBar.debuggingForeground": F.text,
      "statusBar.noFolderBackground": B.editor,
      "statusBar.noFolderForeground": F.muted,
      "statusBarItem.activeBackground": B.active,
      "statusBarItem.hoverBackground": B.hover,
      "statusBarItem.prominentBackground": B.hover,
      "statusBarItem.prominentForeground": F.muted,
      "statusBarItem.remoteBackground": B.sky,
      "statusBarItem.remoteForeground": F.text,
      "statusBarItem.errorBackground": B.clay,
      "statusBarItem.errorForeground": F.text,
      "statusBarItem.warningBackground": B.sand,
      "statusBarItem.warningForeground": F.text,
    }),
    featureGroup("title.bar", {
      "titleBar.activeBackground": B.editor,
      "titleBar.activeForeground": F.text,
      "titleBar.border": B.transparent,
      "titleBar.inactiveBackground": B.editor,
      "titleBar.inactiveForeground": F.faint,
    }),
    featureGroup("menus", {
      "menu.background": B.popup,
      "menu.border": B.transparent,
      "menu.foreground": F.text,
      "menu.selectionBackground": B.active,
      "menu.selectionBorder": B.transparent,
      "menu.selectionForeground": F.text,
      "menu.separatorBackground": B.transparent,
      "menubar.selectionBackground": B.active,
      "menubar.selectionBorder": B.transparent,
      "menubar.selectionForeground": F.text,
    }),
    featureGroup("command.center", {
      "commandCenter.foreground": F.muted,
      "commandCenter.activeForeground": F.text,
      "commandCenter.background": B.editor,
      "commandCenter.activeBackground": B.hover,
      "commandCenter.border": B.transparent,
      "commandCenter.inactiveForeground": F.faint,
      "commandCenter.inactiveBorder": B.transparent,
      "commandCenter.activeBorder": B.transparent,
      "commandCenter.debuggingBackground": withAlpha(B.plum, 0.88),
    }),
    featureGroup("notifications", {
      "notificationCenter.border": B.transparent,
      "notificationCenterHeader.background": B.panel,
      "notificationCenterHeader.foreground": F.text,
      "notificationToast.border": B.transparent,
      "notifications.background": B.popup,
      "notifications.border": B.transparent,
      "notifications.foreground": F.text,
      "notificationsErrorIcon.foreground": F.clay,
      "notificationsInfoIcon.foreground": F.sky,
      "notificationsWarningIcon.foreground": F.sand,
    }),
    featureGroup("quick.input", {
      "quickInput.background": B.popup,
      "quickInput.foreground": F.text,
      "quickInputList.focusBackground": B.active,
      "quickInputList.focusForeground": F.text,
      "quickInputTitle.background": B.panel,
      "pickerGroup.border": B.transparent,
      "pickerGroup.foreground": F.muted,
    }),
    featureGroup("settings", {
      "settings.checkboxBackground": B.panel,
      "settings.checkboxBorder": B.transparent,
      "settings.dropdownBackground": B.panel,
      "settings.dropdownBorder": B.transparent,
      "settings.headerForeground": F.text,
      "settings.modifiedItemIndicator": F.sand,
      "settings.numberInputBackground": B.panel,
      "settings.numberInputBorder": B.transparent,
      "settings.rowHoverBackground": B.hover,
      "settings.sashBorder": B.transparent,
      "settings.textInputBackground": B.panel,
      "settings.textInputBorder": B.transparent,
    }),
    featureGroup("breadcrumbs", {
      "breadcrumb.background": B.editor,
      "breadcrumb.focusForeground": F.text,
      "breadcrumb.foreground": F.faint,
      "breadcrumb.activeSelectionForeground": F.text,
      "breadcrumbPicker.background": B.popup,
    }),
    featureGroup("peek.view", {
      "peekView.border": B.transparent,
      "peekViewEditor.matchHighlightBackground": searchMatch,
      "peekViewResult.fileForeground": F.text,
      "peekViewResult.lineForeground": F.muted,
      "peekViewResult.matchHighlightBackground": searchMatch,
      "peekViewResult.selectionBackground": B.active,
      "peekViewResult.selectionForeground": F.text,
      "peekViewTitle.background": B.popup,
      "peekViewTitleDescription.foreground": F.muted,
      "peekViewTitleLabel.foreground": F.text,
    }),
    featureGroup("git.decorations", {
      "gitDecoration.addedResourceForeground": F.moss,
      "gitDecoration.conflictingResourceForeground": F.sand,
      "gitDecoration.deletedResourceForeground": F.clay,
      "gitDecoration.ignoredResourceForeground": F.faint,
      "gitDecoration.modifiedResourceForeground": F.sky,
      "gitDecoration.renamedResourceForeground": F.moss,
      "gitDecoration.stageDeletedResourceForeground": F.clay,
      "gitDecoration.stageModifiedResourceForeground": F.sky,
      "gitDecoration.submoduleResourceForeground": F.sky,
      "gitDecoration.untrackedResourceForeground": F.moss,
    }),
    featureGroup("scm.graph", {
      "scmGraph.foreground1": F.sand,
      "scmGraph.foreground2": F.clay,
      "scmGraph.foreground3": F.ember,
      "scmGraph.foreground4": F.moss,
      "scmGraph.foreground5": F.plum,
      "scmGraph.historyItemBaseRefColor": F.ember,
      "scmGraph.historyItemHoverAdditionsForeground": F.moss,
      "scmGraph.historyItemHoverDefaultLabelBackground": B.active,
      "scmGraph.historyItemHoverDefaultLabelForeground": F.text,
      "scmGraph.historyItemHoverDeletionsForeground": F.clay,
      "scmGraph.historyItemHoverLabelForeground": B.editor,
      "scmGraph.historyItemRefColor": F.sky,
      "scmGraph.historyItemRemoteRefColor": F.plum,
    }),
    featureGroup("minimap", {
      "minimap.findMatchHighlight": searchHighlight,
      "minimap.selectionHighlight": selectionHighlight,
      "minimap.errorHighlight": F.clay,
      "minimap.warningHighlight": F.sand,
      "minimap.infoHighlight": F.sky,
      "minimap.foregroundOpacity": B.minimap,
      "minimapGutter.addedBackground": B.moss,
      "minimapGutter.deletedBackground": B.clay,
      "minimapGutter.modifiedBackground": B.sky,
      "minimapSlider.activeBackground": F.muted,
      "minimapSlider.background": B.guide,
      "minimapSlider.hoverBackground": F.faint,
    }),
    featureGroup("scrollbars", {
      "scrollbarSlider.activeBackground": withAlpha(F.muted, 0.84),
      "scrollbarSlider.background": withAlpha(B.guide, 0.62),
      "scrollbarSlider.hoverBackground": withAlpha(F.faint, 0.72),
    }),
    featureGroup("charts", {
      "charts.blue": F.sky,
      "charts.foreground": F.text,
      "charts.green": F.moss,
      "charts.lines": B.transparent,
      "charts.orange": F.ember,
      "charts.purple": F.plum,
      "charts.red": F.clay,
      "charts.yellow": F.sand,
    }),
    featureGroup("testing", {
      "testing.iconErrored": F.clay,
      "testing.iconFailed": F.clay,
      "testing.iconPassed": F.moss,
      "testing.iconQueued": F.muted,
      "testing.iconSkipped": F.faint,
      "testing.iconUnset": F.faint,
    }),
    featureGroup("welcome.page", {
      "welcomePage.tileBackground": B.panel,
      "welcomePage.tileHoverBackground": B.hover,
      "welcomePage.tileBorder": B.transparent,
    }),
  ];
};

export const createWorkbenchColors = (C: Palette): Theme["colors"] =>
  mergeFeatureGroups(createWorkbenchFeatureGroups(C));
